### ISSUE TITLE
Energy bar gets stuck at 0

### ISSUE THREAD

**Issue by frenchiveruti** [olsonpm/starbound_health-monitor#1] opened 2018-06-18 02:19 UTC
Hello, I've used your mod, looking for a way to avoid my clumsyness, and I ran into an issue of getting my energy stuck at 0 and not recharging again by itself.
I managed to stuck my energy using my flamethrower.
The energy is no longer stuck once I **buy** the health monitor from infinity express.
Thanks.

**Comment by olsonpm** [comment] 2018-06-18 02:24
thanks for letting me know about the bug, and sorry you had the issue.  I'll make time to look into this tomorrow and probably get back to you with questions on how to reproduce.

For now if you could give me a list of the mods you have installed along with their versions that should help me reproduce your issue.

**Comment by frenchiveruti** [comment] 2018-06-18 05:10
Ok, here's the list:
[mods.txt](https://github.com/olsonpm/starbound_health-monitor/files/2109951/mods.txt)
Sorry if it's just messy I just don't know how to limit the recursivity on the ls command.
The versions of all the mods are all just freshly downloaded from the forum.
I wish I could give you the versions but that's impossible due to the poor organization each developer has when it comes to versioning their mods.

**Comment by olsonpm** [comment] 2018-06-18 05:13
haha no worries.  I haven't touched starbound in a while so I forgot that was the state of things.

**Comment by frenchiveruti** [comment] 2018-06-18 05:17
Ah! also, I installed the mod on an already started character in vanilla game, and all the mods where put together at the same time.

**Comment by olsonpm** [comment] 2018-06-19 06:02
Alright it took me a bit to get the hang of things.  Unfortunately after installing each mod individually and testing the flamethrower, I wasn't able to reproduce your issue.

**Some questions**
- How are you running the game?  Mainly I'm wondering whether you're just playing single player or if you're hosting a server and connecting to it.
- If you start a new character, does the problem persist?
- Would you be comfortable zipping your entire starbound directory and hosting it somewhere for me to download?  e.g. uploading it to dropbox or google drive and sending me a share download link.  You can email the link to me at philip.olson@pm.me if you don't want it to be public.  That would be the most sure-fire way for me to debug this.  If not then I have one idea for you to debug but I'll need to test it out tomorrow before giving you instructions.
- Where did you download `MatterManiMani.pak`?  I found the matter manipulator manipulator mod but it didn't have that same `.pak` file name

**A couple other things**
- I'm not terribly sure about this, but it looks like you didn't install the `ManyTabs` mod properly.  In your `mods.txt` output it shows that directory holds two `.pak` files.  I believe those are supposed to be in the directory above e.g. `mods/many_tabs1.pak` instead of `mods/ManyTabs/many_tabs1.pak`
- In the future, each mod's version should be explicit [on the website](https://i.imgur.com/2xTyg8z.png).  Not everyone follows a standardized version scheme but that doesn't matter.  Because most mods are located in `.pak` files, getting the version via the website is how I get that info.  There might be an easier way (I think there's a mod manager in starbound), but the website works well enough for me.

**Comment by frenchiveruti** [comment] 2018-06-20 16:52
Hi there! Ok I will look into the issue.
I play via a GOG version, and installed the mods manually, regarding manytabs, I didn't know what to do with both files and it doesn't affect where they are placed really, the game recognized the mod just fine. It only quirks with a .zip file that won't be able to open.
Just a question, did you start a new character, played so you don't have the health monitor, then installed the mod, and tried again? Because I installed your mod mid-way into the game because the same reason you made the mod.
Because the issue went away once I got the Health Monitor that your mod includes.
**I will see if I can ship you the files when I'm back home.**
And to be honest, there's not much need to worry as the issue is fixed once I bought the Health Monitor.

**Comment by olsonpm** [comment] 2018-06-20 17:00
> it doesn't affect where they are placed really, the game recognized the mod just fine

If it works then I won't worry about it.  Thanks for clarifying
<br>

> Because the issue went away once I got the Health Monitor that your mod includes.

Ah I missed that part.  I'll try quick tonight to reproduce - I was only testing with the health monitor equipped.
<br>

> I will see if I can ship you the files when I'm back home.

Thanks!
<br>

> there's not much need to worry

Ha I appreciate that - but I don't like the idea of my mod causing issues so I either want to fix my mod or put a notice if another mod is known to be incompatible with mine.

**Comment by olsonpm** [comment] 2018-06-20 17:36
So I just tried without the health monitor equipped as well as starting a character with all the mods except mine, and installing my mod after.  Still couldn't reproduce.  I'll await your upload.

**Comment by frenchiveruti** [comment] 2018-06-22 00:27
Ok! So I was able to re-reproduce the bug. (at least on my save+mods folder attached here).
https://mega.nz/#!b5pmlC6Q!eAZU1dYuAI43npaTVzXeGyUyW7GTbuVVuxUEabXbQMw
Steps:
1.   Throw the Health monitor thingy to the ground
2. Equip flamethrower
3. Use util energy drops to 0.
4. Bug should work as intended.

**Comment by frenchiveruti** [comment] 2018-06-22 00:27
I started the character vainilla, then added all the mods, including yours, and then the bug happened.

**Comment by olsonpm** [comment] 2018-06-22 00:32
Awesome thanks so much.  I'll let you know what I find - might not get to this til tomorrow.

**Comment by frenchiveruti** [comment] 2018-06-22 01:07
It's ok, again I like your mod but chill bro, you've already done more than 90% of mod devs out there just by responding this haha
TBH i expected an answer in like a month, and you did in 3h...

**Comment by olsonpm** [comment] 2018-06-22 01:26
haha.  To give some context, I'm in between jobs working on personal projects to build a resume - no real obligations other than visiting family.  So I've got time.  I also share the irritation that everyone does when something just doesn't work and don't want to be the cause of it.

**Comment by frenchiveruti** [comment] 2018-06-22 15:28
Aah, great then, I feel less guilty. haha

**Comment by olsonpm** [comment] 2018-06-23 16:16
I know you're not in a rush haha - but just fyi I was able to reproduce 👍 .  I thought there would be obvious errors logged to the console but there aren't, so it will take me a bit to dig.  I'll close this issue and release an update when I create a fix.

Thanks again for the files.

**Comment by frenchiveruti** [comment] 2018-06-23 20:23
You're welcome, I hope you can narrow it down!

**Closed as completed** 2018-06-24 17:10 UTC

**Comment by olsonpm** [comment] 2018-06-24 17:13
So it didn't take me too long to fix this which is good.  And the reason I couldn't reproduce was this bug only showed up on windows for some stupid reason!  I usually am on linux unless there's a game that isn't linux compatible.

**Comment by frenchiveruti** [comment] 2018-06-24 21:31
As always, Windows screwing up things haha.
